### ISSUE TITLE
How to infer schema for Int column types 

### ISSUE THREAD

**Issue by yoong93** [crealytics/spark-excel#33]
I am trying to dig into your codes but I am relatively new to scala, so I don't get why this can't infer schema for Integer column. Is there any specific  reason you excluded this type?

**Comment by nightscape** [comment]
I guess the problem is here:
https://github.com/crealytics/spark-excel/blob/master/src/main/scala/com/crealytics/spark/excel/InferSchema.scala#L78-L84
I copied that code from the spark-csv plugin, so it might need some tweaking.
If you want to give it a try you could adapt the [part of the test where we specify which type should get inferred for numeric types](https://github.com/crealytics/spark-excel/blob/master/src/test/scala/com/crealytics/spark/excel/IntegrationSuite.scala#L45) and then try to fix the implementation.
Unfortunately, this won't get a high priority on our side until we run into that problem ourselves :wink:

**Comment by yoong93** [comment]
Thanks! I have one more question. I want to get RDD file, before changing it into dataframe. Is there any way to do this?

**Comment by nightscape** [comment]
Yes, if you instantiate an `ExcelRelation` yourself you should be able to use `buildScan` for that.
