### ISSUE TITLE
Pyspark - issue reading excel data with - “useHeader,” “false”

### ISSUE THREAD

**Issue by abhilfc92** [crealytics/spark-excel#336]
I'm trying to read some excel data into Pyspark Dataframe. I'm using the library: 'com.crealytics:spark-excel_2.11:0.11.1'.

I don't have a header in my data. I'm able to read successfully when reading from column A onwards, but when I'm trying to read from two columns down the line - like [N,O], I get a Dataframe with all nulls.

I've explained the complete issue here:
[https://stackoverflow.com/questions/65520514/pyspark-issue-reading-excel-data-with-useheader-false](url)

Please have a look .
Thanks

**Comment by nightscape** [comment]
Are you sure that in version 0.11 the parameter is still called useHeader? In newer versions it is called header.

**Comment by abhilfc92** [comment]
Yes, because when I write 'header', it says missing param - 'useHeader'.
Also , it's reading fine using  ('useHeader','false') from A2:B4.

**Comment by nightscape** [comment]
Could you try a newer version? It's rather fruitless to analyze bugs if old versions...

**Comment by abhilfc92** [comment]
Hi
At first I tried with - **com.crealytics:spark-excel_2.12:0.13.1**.
But that's not able to read at all. Gives me below error:

`
py4j.protocol.Py4JJavaError: An error occurred while calling o91.load.
: java.lang.NoSuchMethodError: scala.Product.$init$(Lscala/Product;)V
        at com.crealytics.spark.excel.Utils$MapIncluding.<init>(Utils.scala:9)
        at com.crealytics.spark.excel.WorkbookReader$.<init>(WorkbookReader.scala:31)
        at com.crealytics.spark.excel.WorkbookReader$.<clinit>(WorkbookReader.scala)
        at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:28)
        at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:18)
        at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:12)
        at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:341)
        at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:239)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:227)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:174)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:748)
`

**Comment by nightscape** [comment]
Then your PySpark probably uses Scala 2.11.
Either you switch to a PySpark based on Scala 2.12 (recommended) or you use the `_2.11` version of spark-excel.

**Comment by abhilfc92** [comment]
Ok, I'll try
thanks

**Comment by TrafalgarLaw-24** [comment]
Hi @abhilfc92  Which environment are you using to run your Pyspark?? Because if you can upgrade or use Pyspark 3.0.1, scala 2.12 comes along with it and you can then use com.crealytics:spark-excel_2.12:0.13.4
After this you should be able to read it fine. This I have tried and it works. 

Or you can just try with com.crealytics:spark-excel_2.11:0.13.4 in your current environment and see if it works. I didn't try this.

**Comment by TrafalgarLaw-24** [comment]
Hey @nightscape I'm facing a similar issue as abhilfc92's but the solutions I already know doesn't work. So we're using AWS Glue V2 which is the latest available in AWS. The spark version of it is 2.4.3 and it's corresponding scala version is 2.11. We don't have options to use higher versions of spark or scala. So after a lot of research and testing 'spark-excel_2.11-0.12.0' seemed to satisfy the conditions I have. But I got the below error when I tried to read an excel. Can you please check and help me clear this. My df read statement is 
sample_df = spark.read.format("com.crealytics.spark.excel").option("useHeader", True).option("inferschema", "true").load('s3://bucket-name/samp.xlsx')
The above read statement worked well with com.crealytics:spark-excel_2.12:0.13.4 when I used spark 3.0.1 and scala 2.12

An error occurred while calling o90.load. : java.io.IOException: org/apache/xmlbeans/XmlObject at shadeio.poi.ss.usermodel.WorkbookFactory.createWorkbook(WorkbookFactory.java:326) at shadeio.poi.ss.usermodel.WorkbookFactory.createXSSFWorkbook(WorkbookFactory.java:296) at shadeio.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:214) at shadeio.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:180) at com.crealytics.spark.excel.DefaultWorkbookReader$$anonfun$openWorkbook$1.apply(WorkbookReader.scala:42) at com.crealytics.spark.excel.DefaultWorkbookReader$$anonfun$openWorkbook$1.apply(WorkbookReader.scala:42) at scala.Option.fold(Option.scala:158) at com.crealytics.spark.excel.DefaultWorkbookReader.openWorkbook(WorkbookReader.scala:42) at com.crealytics.spark.excel.WorkbookReader$class.withWorkbook(WorkbookReader.scala:14) at com.crealytics.spark.excel.DefaultWorkbookReader.withWorkbook(WorkbookReader.scala:38) at com.crealytics.spark.excel.ExcelRelation.excerpt$lzycompute(ExcelRelation.scala:31) at com.crealytics.spark.excel.ExcelRelation.excerpt(ExcelRelation.scala:31) at com.crealytics.spark.excel.ExcelRelation.headerCells$lzycompute(ExcelRelation.scala:33) at com.crealytics.spark.excel.ExcelRelation.headerCells(ExcelRelation.scala:33) at com.crealytics.spark.excel.ExcelRelation$$anonfun$inferSchema$1.apply(ExcelRelation.scala:148) at com.crealytics.spark.excel.ExcelRelation$$anonfun$inferSchema$1.apply(ExcelRelation.scala:147) at scala.Option.getOrElse(Option.scala:121) at com.crealytics.spark.excel.ExcelRelation.inferSchema(ExcelRelation.scala:147) at com.crealytics.spark.excel.ExcelRelation.<init>(ExcelRelation.scala:40) at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:40) at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:18) at com.crealytics.spark.excel.DefaultSource.createRelation(DefaultSource.scala:12) at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:318) at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223) at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211) at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244) at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357) at py4j.Gateway.invoke(Gateway.java:282) at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132) at py4j.commands.CallCommand.execute(CallCommand.java:79) at py4j.GatewayConnection.run(GatewayConnection.java:238) at java.lang.Thread.run(Thread.java:748) Caused by: java.lang.NoClassDefFoundError: org/apache/xmlbeans/XmlObject at shadeio.poi.xssf.usermodel.XSSFWorkbookFactory.createWorkbook(XSSFWorkbookFactory.java:83) at shadeio.poi.xssf.usermodel.XSSFWorkbookFactory.createWorkbook(XSSFWorkbookFactory.java:130) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at shadeio.poi.ss.usermodel.WorkbookFactory.createWorkbook(WorkbookFactory.java:314) ... 36 more Caused by: java.lang.ClassNotFoundException: org.apache.xmlbeans.XmlObject at java.net.URLClassLoader.findClass(URLClassLoader.java:382) at java.lang.ClassLoader.loadClass(ClassLoader.java:418) at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ... 43 more

**Comment by nightscape** [comment]
@TrafalgarLaw-24 it might be that you have to explicitly have to add the xmlbeans dependency to the classpath.

**Comment by TrafalgarLaw-24** [comment]
Hey @nightscape You're right. I thought of that too and added xml beans jar. After adding that another error related to 'poi' appeared. So I guess I have to manually add all the dependencies listed on the package details. But my concern is if the jar is built using all the dependencies then why again it's throwing all these errors?

**Comment by nightscape** [comment]
The Jar does not contain all dependencies, only the ones that need to be shaded in order to avoid conflicts with e.g. Spark's built-in packages.
The pom.xml in the Maven repository should actually contain a list of the not included dependencies. In Scala/Java build tools it will resolve and download these dependencies automatically, but maybe in PySpark that works differently...

**Comment by TrafalgarLaw-24** [comment]
Okay let me try to add all those jars and see how it works out. Anyway thanks for the prompt response!

**Comment by TrafalgarLaw-24** [comment]
Hey @nightscape It worked. I added all the jars mentioned in the POM with correct versions for my requirement and I'm able to read the excel file as well as write one.

**Comment by quanghgx** [comment]
It looks like both of the issues ("header" option, and dependencies) are resolved. Would like to resolve it. Thanks to @TrafalgarLaw-24 and @abhilfc92 
For further detail about the dependencies, this [wiki page](https://github.com/crealytics/spark-excel/wiki#setup-spark-excel) might be some help.
Sincerely,
