### ISSUE TITLE
Hi @nightscape , Seems like it ignores that column altogether. Attaching a screenshot for that. Anyways I was able to use workaround (custom schema) and get my requirement done.

### ISSUE THREAD

**Issue by mahajanjanvi** [crealytics/spark-excel#394]
Hi @nightscape , Seems like it ignores that column altogether. Attaching a screenshot for that. Anyways I was able to use workaround (custom schema) and get my requirement done.

<img width="520" alt="issue" src="https://user-images.githubusercontent.com/13267258/66254938-f2714480-e79a-11e9-8230-a6c21075e4ee.PNG">

_Originally posted by @AyubmmD in https://github.com/crealytics/spark-excel/issues/122#issuecomment-538646186_

**Comment by nightscape** [comment]
?

**Comment by quanghgx** [comment]
Hi @mahajanjanvi ,
1+ with @nightscape in [a issue 122's comment](https://github.com/crealytics/spark-excel/issues/122#issuecomment-538594886) , this issue is fixed in later versions.
 
I've just tried with the latest version with the TestFile.xlsx that @AyubmmD shared in #122, the result is fine.
![Screenshot from 2021-09-04 22-59-42](https://user-images.githubusercontent.com/22023385/132100799-01b16e28-4cec-4d9c-880e-62039024cd05.png)

Here is my paragraph:
```python
df = spark.read.format("excel") \
   .option("header", True) \
   .option("inferSchema", True) \
   .load(f"/home/quanghgx/Downloads/TestFile.xlsx")

df.show(10)
df.printSchema()
```
Please take a took if you have time, @mahajanjanvi

**Comment by quanghgx** [comment]
Going to resolve this ticket, however, feel free to re-open it!
Sincerely,
