### ISSUE TITLE
Row containing a cell with data #N/A gets read with NULL values for all columns

### ISSUE THREAD

**Issue by sidrahsayyad** [crealytics/spark-excel#407]
I am using the spark-excel_2.11-0.11.1.jar with pyspark to read data from an excel file into a dataframe and then create a physical table out of it. Whenever any row in excel has data in a cell of the type #N/A, the entire row gets read with NULL values:
Excel file:
![image](https://user-images.githubusercontent.com/33220103/131452874-60ada951-0dba-40db-b247-30cd04b56867.png)
Physical table:
![image](https://user-images.githubusercontent.com/33220103/131452971-07d48cdc-7b0b-48ba-aec9-7d789df3b632.png)
The entire row data should not be read as NUL here.

**Comment by nightscape** [comment]
Please try the newest version before reporting bugs.

**Comment by AshutoshSundriyal** [comment]
I tried the same using spark-excel_2.11-0.13.7.jar with pyspark to read data from an excel file into a dataframe and got the same outcomes as above i.e whenever any row in excel has data in a cell of the type #N/A, the entire row gets read with NULL values

**Comment by nightscape** [comment]
Could you try`0.14.0` and `0.14.0+6-a77fdf30-SNAPSHOT`?

**Comment by quanghgx** [comment]
Hi @AshutoshSundriyal and @sidrahsayyad 
1+ with @nightscape , please take a try with spark-excel 0.14.0
 
I did create an excel file with google spreadsheet, download to a local folder, then load it with spark-excel on jupyter notebook. 
![Screenshot from 2021-09-04 22-24-04](https://user-images.githubusercontent.com/22023385/132099773-61aff0dd-a1e5-4c34-a0b7-38f939b84795.png)

The result look fine with spark-excel 0.14.0
![Screenshot from 2021-09-04 22-25-58](https://user-images.githubusercontent.com/22023385/132099789-fdbb8c45-f63f-4393-a940-3e5eb8da94c8.png)
Note, the extra all null rows are expected. In the google spreadsheet, I did (accidentally) define formatting for more rows than actually needed.

PS: In case you have time to take a try on your side.
Whole notebook
```python
from pyspark.sql import SparkSession
from pyspark.sql.functions import input_file_name

# Please change to your path!!!
ROOT="/home/quanghgx/spark-excel"

# Assembly or download spark-excel and its dependencies
jars = [
    "/home/quanghgx/spark-excel/target/scala-2.12/spark-excel_2.12-3.1.2_0.14.0+8-4b62d9c5-SNAPSHOT.jar",
    "/home/quanghgx/jars/poi-ooxml-schemas-4.1.2.jar",
    "/home/quanghgx/jars/commons-collections4-4.4.jar",
    "/home/quanghgx/jars/xmlbeans-3.1.0.jar"
]

spark = SparkSession \
    .builder \
    .appName("Python Spark SQL basic example") \
    .config("spark.jars", ",".join(jars)) \
    .getOrCreate()

df = spark.read.format("excel") \
   .option("header", True) \
   .option("inferSchema", True) \
   .load(f"/home/quanghgx/Desktop/spark-excel-issue_407.xlsx")

df.show(10)
df.printSchema()
```
Result in text:
```bash
+----+----+-------------------+
| co1|col2|               col3|
+----+----+-------------------+
|   1| abc|1991-12-20 00:00:00|
|   2| def|1992-12-20 00:00:00|
|   3| ghi|1993-12-20 00:00:00|
|   4| hij|               null|
|   5| klm|1995-12-20 00:00:00|
|   6|#N/A|1996-12-20 00:00:00|
|null|null|               null|
|null|null|               null|
|null|null|               null|
|null|null|               null|
+----+----+-------------------+
only showing top 10 rows

root
 |-- co1: integer (nullable = true)
 |-- col2: string (nullable = true)
 |-- col3: timestamp (nullable = true)
```

The excel file is attached to this message
[spark-excel-issue_407.xlsx](https://github.com/crealytics/spark-excel/files/7110111/spark-excel-issue_407.xlsx)

**Comment by quanghgx** [comment]
Going to resolve this ticket, however, feel free to re-open it!
Sincerely,

**Comment by AshutoshSundriyal** [comment]
Hi @quanghgx,
I did executed the provided code with the below modifications
`from pyspark.sql import SparkSession
from pyspark.sql.functions import input_file_name

jars = [
    "/test/jars/spark-excel_2.12-0.14.0.jar",
    "/test/jars/poi-ooxml-schemas-4.1.2.jar",
    "/test/jars/commons-collections4-4.4.jar",
    "/test/jars/xmlbeans-3.1.0.jar"
]

spark = SparkSession \
    .builder \
    .appName("test") \
    .config("spark.jars", ",".join(jars)) \
    .getOrCreate()

df = spark.read.format("excel") \
   .option("header", True) \
   .option("inferSchema", True) \
   .load("/mnt/spark-excel-issue.xlsx")`
   
   But this seems to throw me an class not found exception(screenshot attached)
![image](https://user-images.githubusercontent.com/32016918/134152483-a109d83a-51c7-432c-af53-68c4e62241a7.png)

**Comment by AshutoshSundriyal** [comment]
Hi @quanghgx ,
While trying to create a jar using `sbt -Dspark.testVersion=2.4.5 assembly`, ran into the following errors
![image](https://user-images.githubusercontent.com/32016918/134302320-1dfe7d19-242c-4b76-9888-80fd7469e2b4.png)
Can you please help us build a spark-excel jar for our spark-version 2.4.5.

**Comment by quanghgx** [comment]
Hi @AshutoshSundriyal 

Here you are [spark-excel_2.12-2.4.5_0.14.0+18-356e02b4-SNAPSHOT.zip](https://github.com/crealytics/spark-excel/files/7210967/spark-excel_2.12-2.4.5_0.14.0%2B18-356e02b4-SNAPSHOT.zip)
(Zipped, because git does not allow to attach .jar file. Please use a sandbox environment when running above jar. I don't feel comfortable in providing runnable binary)

Here is my sbt version, in hope it might helps
![Screenshot from 2021-09-22 20-22-20](https://user-images.githubusercontent.com/22023385/134351635-a28362f4-f1b6-4f99-a090-033fc0aaf5d3.png)

Sincerely,

**Comment by AshutoshSundriyal** [comment]
Hi @quanghgx 
we in our project are using Scala 2.11.12 , where as i think this jar won't be compatible with this version of Scala? if not, is there some way we could achieve this by staying at Scala 2.11.12.

**Comment by quanghgx** [comment]
Hi @AshutoshSundriyal 
Here is version with scala 2.11:
[spark-excel_2.11-2.4.5_HEAD+20210924-0210.zip](https://github.com/crealytics/spark-excel/files/7220268/spark-excel_2.11-2.4.5_HEAD%2B20210924-0210.zip)

I do think we need to do something about the dependencies of spark-excel. 

PS: Here are (adhoc) steps that I used to produce above jar with docker (I think, we can apply similar step with an Ubuntu 18.04 virtual machine)

0. Assume that, we have working docker, and in Linux (you are seem in Windows)
1. [docker] Follow this guide https://opensource.com/article/20/4/how-containerize-build-system
2. [docker] With additional sbt binary downloaded to swbuilder folder
3. [spark-excel] Checkout this commit, because spoiwo2 does not have scala 2.11 binary (yet?): https://github.com/crealytics/spark-excel/commit/f60f9b1234b9ec64faa6643f46319f1ca75e53b4
4. [spark-excel] Remove test dependencies (due to same reason with spoiwo2)

[install_swbuilder.dockerfile.zip](https://github.com/crealytics/spark-excel/files/7220362/install_swbuilder.dockerfile.zip)
[build.sbt.zip](https://github.com/crealytics/spark-excel/files/7220360/build.sbt.zip)

**Comment by AshutoshSundriyal** [comment]
Hi @quanghgx,
The above jar has resolved the initial issue we were facing where the entire row gets rejected if any of the column contained "#N/A". Now it replaces the particular cell containing "#N/A" with null.

**Comment by quanghgx** [comment]
Thanks @AshutoshSundriyal for your update.
Will ping you when spark-excel publish binary for spark 2.4.5 with scala 2.11

**Comment by AshutoshSundriyal** [comment]
@quanghgx is there any tentative date by when we can expect this roll out.
