### ISSUE TITLE
the parameter [scientific notations] not work when inferSchema is ture

### ISSUE THREAD

**Issue by cyxinda** [crealytics/spark-excel#460]
## Expected Behavior
1. I set the config: inferSchema= true and usePlainNumberFormat=true,such as the  picture:
![图片](https://user-images.githubusercontent.com/7237898/142634050-289dbfb3-bd90-4cb6-8a1c-c47eeb597e4d.png)
the data loaded from excel (*.xlsx) to the hive table is as follow:
![图片](https://user-images.githubusercontent.com/7237898/142712593-b2789e2c-3f2b-4cb8-984a-4d53b860e9d6.png)

The type of the field id/imei is double,the values of id/imei will be loaded as scientific notations.this behivor is not accord for  the config of [usePlainNumberFormat=true].
Also, the field of  order_open_time is date ,the values of order_open_time is correct.

2. When I set  inferSchema= false ,and usePlainNumberFormat=true,such as the  picture:
![图片](https://user-images.githubusercontent.com/7237898/142711914-58ddd0b1-4591-4ca6-a180-c385ff1295af.png)
the data loaded from excel (*.xlsx) to the hive table is as follow:
![图片](https://user-images.githubusercontent.com/7237898/142712574-981c4123-c2d8-4cdf-85f9-e25adcd571c9.png)

The values of id/imei will be loaded correct without rounding and scientific notations .But the field of  order_open_time value is not normal.

I don't know how to resolve the problem.And ask for your help.

## Your Environment
I use the Spark-Excel version:
`
            <dependency>
                <groupId>com.crealytics</groupId>
                <artifactId>spark-excel_2.12</artifactId>
                <version>0.14.0</version>
            </dependency>
`
the  excel is *.xlsx
Spark version and language ：
spark:spark-3.1.1-bin-hadoop3.2
Scala:12
jdk:1.8
Operating System and version, cluster environment, ...:
centos7.9

**Comment by quanghgx** [comment]
Hi @cyxinda 

`usePlainNumberFormat` is for writing. It means, if this parameter is set to true, the Double/Float value will use plain number format in the output cell. This is for default display only, not related to underlining value of given cell.

For your case, it's expected behavior. Let me explain a bit:
   * With schema inferring, it will try to suggest the tightness type possible for all values of each column
   * id, imei, seem contain all numerical value --> so it use Double type. This is correct. The same for order_open_time

With above understanding, if we want id and imei to be as it's; Like keeping the 0 prefix or don't want to loss precision with Float/Double, we can ask spark-excel to treat these field as String.
* Solution A: Either with inferSchema=false (for all field) - you already tested, combine with cast order_open_time to Timestamp() type after loaded into data frame.
* Solution B: Or p**ass a custom schema.** (detail bellow)

P**assing custom sche**ma (Solution B):
1. With a simple excel file with google spreadsheet, follow (loosely) with your screenshot. 
2. Create and pass custom schema
```python
from pyspark.sql.types import StructType, StructField, StringType, DoubleType, TimestampType

schema = StructType([StructField('SERVICE_MACHINE_MTM', StringType(),True),
                     StructField('SERVICE_MACHINE_TYPE', StringType(), True),
                     StructField('SERVICE_MACHINE_IMEI', StringType(), True),
                     StructField('CARY_IN_TIME', TimestampType(), True)])

df = spark.read.format("excel") \
   .option("header", True) \
   .schema(schema) \
   .option("inferSchema", False) \
   .load("/home/quanghgx/Downloads/issue_460.xlsx") \
   .withColumnRenamed("SERVICE_MACHINE_MTM", "mtm") \
   .withColumnRenamed("SERVICE_MACHINE_TYPE", "xcvr") \
   .withColumnRenamed("SERVICE_MACHINE_IMEI", "imei") \
   .withColumnRenamed("CARY_IN_TIME", "order_open_time")

df.printSchema()
df.show(10)
```
3. Result
```python
root
 |-- mtm: string (nullable = true)
 |-- xcvr: string (nullable = true)
 |-- imei: string (nullable = true)
 |-- order_open_time: timestamp (nullable = true)

+-----------+-----+--------------------+-------------------+
|        mtm| xcvr|                imei|    order_open_time|
+-----------+-----+--------------------+-------------------+
|1.234567891|TypeA|10203040506070809...|2021-01-15 10:00:00|
|2.234567891|TypeB|10203040506070809...|2021-02-15 11:10:00|
|3.234567891|TypeC|10203040506070809...|2021-03-15 12:20:00|
|4.234567891|TypeD|10203040506070809...|2021-04-15 13:30:00|
+-----------+-----+--------------------+-------------------+
```
Excel file:
[issue_460.xlsx](https://github.com/crealytics/spark-excel/files/7573960/issue_460.xlsx)

**Comment by cyxinda** [comment]
hi
I guess the problem due to my lack of knowledge of double value stored in hive.There are no problem in crealytics.
when I transfer the field type from Double to Long or String，It will be OK.
thank you.


发自我的iPhone
