### ISSUE TITLE
Remove shading of packages for POI?

### ISSUE THREAD

**Issue by pjfanning** [crealytics/spark-excel#596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

@nightscape If you see https://github.com/crealytics/spark-excel/issues/590#issuecomment-1133610010 - the shading makes pointing users to useful POI configs difficult.

Is there really a use case why someone who uses spark-excel with its shaded POI and who would then also use a different version of the actual POI classes in the same JVM? Seems like a very unlikely scenario to me. 

### Environment

```markdown
- Spark version:
- Spark-Excel version:
- OS:
- Cluster environment
```

**Comment by nightscape** [comment]
Hi @pjfanning, afair there was some issues with non-shaded POI, but I couldn't find the issue.
I found [@EnverOsmanov's PR](https://github.com/crealytics/spark-excel/pull/184) to also un-shade POI.
I'd be willing to give it a try in a draft release, so that we don't base decisions on my (admittedly not too good) memory 😉 
Would you mind opening a PR?

**Comment by nightscape** [comment]
Draft release available as `0.18.0-beta2`.

**Comment by pjfanning** [comment]
0.18.0 is released

**Comment by nightscape** [comment]
@pjfanning thanks a lot for your contributions to spark-excel!!
